<a href="https://colab.research.google.com/github/thinkGrow/Neural-Network-CSC424/blob/main/nn_1_assignment_v1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torchvision
import torchvision.transforms as transforms
import numpy as np

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True)

x_train = trainset.data
x_test = testset.data
y_train = np.array(trainset.targets)
y_test = np.array(testset.targets)

dimension_two = x_train.shape[1]*x_train.shape[2]*x_train.shape[3] #3072 from 50,000x32x32x3

x_train = x_train.reshape(x_train.shape[0], dimension_two) #50,000 x 3072
x_test = x_test.reshape(x_test.shape[0], dimension_two) #50,000 x 3072

Files already downloaded and verified
Files already downloaded and verified


In [ ]:
# import numpy as np
# A = np.arange(12).reshape(4,3)

# x = np.array([5,5,5])

# A

# A-x

# np.abs(A-x)

# distances = np.sum(np.abs(A-x), axis=1)
# distances

# # distance_sort = np.argsort(distances)[:1] 
# distance_sort = np.argsort(distances)[:3]
# distance_sort

In [ ]:
# distances = np.sum(np.abs(x_train - x_test[0,:] ), axis = 1) 
# distance_sort = np.argsort(distances)[:3] 

# print(distance_sort)

In [ ]:
class KNearestNeighbor(object): 
    def __init__(self):
        pass
    
    def train(self,x_train,y_train):         
        self.x_train = x_train
        self.y_train = y_train
        
    
    def predict(self,x_test,k):        
        dimension_one = x_test.shape[0] #50000
        y_predict = np.zeros(dimension_one, dtype = self.y_train.dtype) #(50000,)
        
        for i in range(dimension_one):

            distances = np.sum(np.abs(self.x_train - x_test[i,:] ), axis = 1) 
            minimum_ind = np.argsort(distances)[:k] 
            
            bincount = np.bincount(self.y_train[minimum_ind]) #no of occurences of the minimum value
            #if the closest k points have unique labels, give the first one
            #if not unique, give modal
            y_predict[i] = bincount.argmax()                 

        return y_predict
                
# y_predict = np.zeros(shape=(1, x_test.shape[0]))

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

def conclusion(y_test, y_predict):
    print("Confusion Matrix: \n", confusion_matrix(y_test, y_predict), "\n")
    print("Accuracy: ", accuracy_score(y_test, y_predict), "\n")
    print("F-score:\n", f1_score(y_test, y_predict, average = None), "\n")

In [ ]:
knn = KNearestNeighbor()
knn.train(x_train, y_train)
y_predict = knn.predict(x_test,1)
conclusion(y_test, y_predict)

Confusion Matrix: 
 [[524  24 155  24  31  18  42  12 161   9]
 [189 126  99  68  81  71  53  30 236  47]
 [233   2 313  88 140  65  52  20  76  11]
 [196  17 161 171 106 146  86  28  80   9]
 [178   6 259  66 246  80  51  16  94   4]
 [195   7 138 149  82 242  60  37  82   8]
 [114   3 233 114 154 124 165  10  78   5]
 [190  16 167  99 160  65  65 133  88  17]
 [273  45  64  32  36  27  17  16 481   9]
 [219  89  76  64  60  74  53  42 232  91]] 

Accuracy:  0.2492 

F-score:
 [0.31652069 0.18876404 0.23489681 0.1824     0.23473282 0.25313808
 0.20072993 0.19791667 0.36886503 0.15041322] 



In [ ]:
knn = KNearestNeighbor()
knn.train(x_train, y_train)
y_predict = knn.predict(x_test,3)
conclusion(y_test, y_predict)

Confusion Matrix: 
 [[670  20 118  14  20   4   9   4 140   1]
 [359 135 108  64  71  36  16  11 187  13]
 [376   7 362  60  94  34  15   5  45   2]
 [362  21 205 154  62 101  36   9  50   0]
 [298  10 321  59 187  39  17   5  64   0]
 [326  16 201 151  64 148  27  14  51   2]
 [242  10 316  98 112  71  98   5  48   0]
 [335  20 210  93 130  41  23  82  60   6]
 [355  45  45  20  23  22   5  11 470   4]
 [347 104 104  68  50  54  16  21 203  33]] 

Accuracy:  0.2339 

F-score:
 [0.2869379  0.1945245  0.24214047 0.17293655 0.20628792 0.19096774
 0.15530903 0.14053128 0.405522   0.06220547] 



In [ ]:
knn = KNearestNeighbor()
knn.train(x_train, y_train)
y_predict = knn.predict(x_test,5)
conclusion(y_test, y_predict)

Confusion Matrix: 
 [[670  20  95  14  22  10  15   4 149   1]
 [316 114  87  51  87  39  35  21 223  27]
 [329   2 393  37  99  46  19  12  62   1]
 [319  18 175 161  88 118  41  11  68   1]
 [272   7 304  51 227  49  17   5  68   0]
 [275   8 207 138  70 176  40  10  69   7]
 [202   7 295  87 135  92 113   7  62   0]
 [295  17 194  60 159  67  34  92  73   9]
 [357  37  36  17  27  16   9  15 483   3]
 [304  74  87  51  54  61  23  38 257  51]] 

Accuracy:  0.248 

F-score:
 [0.30882692 0.17484663 0.27358162 0.19316137 0.23069106 0.21027479
 0.1679049  0.15144033 0.38424821 0.09272727] 

